### ISSUE TITLE
Steps/documentation to create encryption certificate?

### ISSUE THREAD

**Issue by aarpy** [auth0/passport-wsfed-saml2#66]
Hello - First of all, thanks for nice and clean package to integrate with ADFS. 

We are able to integrate/test with ADFS successfully, however, when encryption is enabled on Relying party trust using self-signed certificate, the wsfed library cert is unable to decrypt the XML.  I could not find documentation what cert need to provided/generated.

I have looked through documentation and examples without luck.  Can any share the details?

Error Message:
```
Error: Signature is missing (xpath: .//*[local-name(.)='Signature' and namespace-uri(.)='http://www.w3.org/2000/09/xmldsig#'])
    at SAML.validateSignature (/Users/test/test/adfs_test2/node_modules/passport-wsfed-saml2/lib/passport-wsfed-saml2/saml.js:45:21)
    at SAML.validateSamlAssertion (/Users/test/test/adfs_test2/node_modules/passport-wsfed-saml2/lib/passport-wsfed-saml2/saml.js:300:8)
    at /Users/test/test/adfs_test2/node_modules/passport-wsfed-saml2/lib/passport-wsfed-saml2/strategy.js:71:16
    at Object.retrieveToken (/Users/test/test/adfs_test2/node_modules/passport-wsfed-saml2/lib/passport-wsfed-saml2/wsfederation.js:62:5)
    at WsFedSaml2Strategy._authenticate_saml (/Users/test/test/adfs_test2/node_modules/passport-wsfed-saml2/lib/passport-wsfed-saml2/strategy.js:66:15)
    at loaded (/Users/test/test/adfs_test2/node_modules/passport-wsfed-saml2/lib/passport-wsfed-saml2/strategy.js:175:16)
    at NullStore.verify (/Users/test/test/adfs_test2/node_modules/passport-wsfed-saml2/lib/passport-wsfed-saml2/state/null.js:9:3)
    at verifyState (/Users/test/test/adfs_test2/node_modules/passport-wsfed-saml2/lib/passport-wsfed-saml2/strategy.js:158:26)
    at executeWsfed (/Users/test/test/adfs_test2/node_modules/passport-wsfed-saml2/lib/passport-wsfed-saml2/strategy.js:179:7)
    at WsFedSaml2Strategy.authenticate (/Users/test/test/adfs_test2/node_modules/passport-wsfed-saml2/lib/passport-wsfed-saml2/strategy.js:286:5)
::1 - - [24/Dec/2017:16:01:18 +0000] "POST /login/callback HTTP/1.1"
```

Code setup:
```
passport.use(new wsfedsaml2(
  {
    path: 'https://domain.ngrok.io/login/callback',
    realm: 'urn:domain:dashboard',
    homeRealm: '', // specify an identity provider to avoid showing the idp selector
    identityProviderUrl: 'https:///server.domain.local/adfs/ls',
    // setup either a certificate base64 encoded (cer) or just the thumbprint of the certificate if public key is embedded in the signature
    cert: fs.readFileSync('./certs/key.pem').toString('base64')
    // thumbprints: ['A9D596B7A1C71EA3CF4B330DE']
  },
```

Self signed cert generation (on Mac):
```
 openssl req -newkey rsa:2048 -nodes -keyout key.pem -x509 -days 365 -out certificate.pem
openssl x509 -outform der -in certificate.pem -out certificate.cer
```

**Comment by mikeops** [comment]
It looks like you probably meant to use `certificate.pem` instead of `key.pem`.
